# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Netg < Formula
  desc "Modern lightweight network scanner"
  homepage "https://github.com/daddylix99/netg-dist"
  version "1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/daddylix99/netg-dist/releases/download/v1.5/netg_darwin_amd64.tar.gz"
      sha256 "cf7a21fa2f622394850ee9eb6785b480cd9dfee487d3f6eab335780e5571890a"

      define_method(:install) do
        bin.install "netg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/daddylix99/netg-dist/releases/download/v1.5/netg_darwin_arm64.tar.gz"
      sha256 "0212d1cafd8e1be9841489fa506be9be4ffed56588c1bf7bdec5501d5eee0ae1"

      define_method(:install) do
        bin.install "netg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/daddylix99/netg-dist/releases/download/v1.5/netg_linux_amd64.tar.gz"
      sha256 "1fedbe45b7cffd51262a6fc6459fff34f05ce74e06584a57c68f1c145688ca93"
      define_method(:install) do
        bin.install "netg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/daddylix99/netg-dist/releases/download/v1.5/netg_linux_arm64.tar.gz"
      sha256 "e2b7e9468f4de30dd811e6cba03661014afb49df6c2281628f15fcbdb13e2be3"
      define_method(:install) do
        bin.install "netg"
      end
    end
  end
end
