# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Netg < Formula
  desc "Modern lightweight network scanner"
  homepage "https://github.com/ExVoider/netg-dist"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ExVoider/netg-dist/releases/download/v0.0.3/netg_darwin_amd64.tar.gz"
      sha256 "fab4b6a9e9a6aad4ce85ffbee822bbea1dd135b17ce4628274c7910994fd2afe"

      define_method(:install) do
        bin.install "netg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ExVoider/netg-dist/releases/download/v0.0.3/netg_darwin_arm64.tar.gz"
      sha256 "732d47dbbc7c93aca7926defb09e8b47f610faa23e2ca4a36ac09bee68abbcdd"

      define_method(:install) do
        bin.install "netg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ExVoider/netg-dist/releases/download/v0.0.3/netg_linux_amd64.tar.gz"
      sha256 "468825d02113dee2578cf6c4fc67dc32eb59d633e7edf001f20b059be0098d46"
      define_method(:install) do
        bin.install "netg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ExVoider/netg-dist/releases/download/v0.0.3/netg_linux_arm64.tar.gz"
      sha256 "aefe406b6565da8235734d0556fcc68a4d276324cbd27e4cac78eae77a4e864a"
      define_method(:install) do
        bin.install "netg"
      end
    end
  end
end
