# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Netg < Formula
  desc "Modern lightweight network scanner"
  homepage "https://github.com/daddylix99/netg-dist"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/daddylix99/netg-dist/releases/download/v0.0.2/netg_darwin_amd64.tar.gz"
      sha256 "7c049100c4a7748afb824ec4be0839d66600ed43e82c2ab54161448aa94aee54"

      define_method(:install) do
        bin.install "netg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/daddylix99/netg-dist/releases/download/v0.0.2/netg_darwin_arm64.tar.gz"
      sha256 "1b0c83682965a76d9347454e00eceee6b6e57c0704e50d9621acd3b8b993c694"

      define_method(:install) do
        bin.install "netg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/daddylix99/netg-dist/releases/download/v0.0.2/netg_linux_amd64.tar.gz"
      sha256 "f72b90d103a8e9216d5453a16cc71b8bfca498e3dc9eae1e881eebd9e793e067"
      define_method(:install) do
        bin.install "netg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/daddylix99/netg-dist/releases/download/v0.0.2/netg_linux_arm64.tar.gz"
      sha256 "d1fdf85ee4812a2225a712bfc4ae609ff7258ad13eeaf149229e0eb21d584df9"
      define_method(:install) do
        bin.install "netg"
      end
    end
  end
end
